### ISSUE TITLE
runtime error in run_cray_tests.py

### ISSUE THREAD

**Issue by jswaro** [ofi-cray/cray-tests#38]
```
cray-tests(GUPS**) $ python scripts/run_cray_tests.py
Starting: ./rdm_pingpong -t1
Failed to start: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "scripts/run_cray_tests.py", line 318, in <module>
    sys.exit(_main())
  File "scripts/run_cray_tests.py", line 290, in _main
    sys.stdout.write('Skipping %s\n'%(t[0]))
```

Simple issue. 't' appears to be used where another variable was more likely. I suspect that 'i' was meant to be used from the enumeration.

**Comment by jswaro** [comment]
@sungeunchoi
